<?php

namespace Database\Seeders;

use App\Models\Admin\Product\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $product = [
            [
                'name' => 'Salt',
                'purchaseprice' => 80,
                'sellingprice' => 100,
                'sku' => 'SKU-01',
                'productcategory_id' => 5,
                'uom_id' => 3,
                'cgst' => 2.5,
                'sgst' => 2.5,
                'igst' => 5,
                'cess' => 2,
                'hsncode' => 0321,
            ],
            [
                'name' => 'Ghee',
                'purchaseprice' => 200,
                'sellingprice' => 250,
                'sku' => 'SKU-02',
                'productcategory_id' => 2,
                'uom_id' => 2,
                'cgst' => 6,
                'sgst' => 6,
                'igst' => 12,
                'cess' => 3,
                'hsncode' => 0123,
            ],
            [
                'name' => 'Chicken',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 3,
                'uom_id' => 1,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0213,
            ],
            [
                'name' => 'Tomato',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 4,
                'uom_id' => 1,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0413,
            ],
            [
                'name' => 'Drinks',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 5,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Sugar',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 5,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Wheat',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 5,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Papaya',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Mango',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Apple',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Banana',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Rice',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Dates',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Cashew Nuts',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Walnut',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
            [
                'name' => 'Dry grapes',
                'purchaseprice' => 45,
                'sellingprice' => 55,
                'sku' => 'SKU-03',
                'productcategory_id' => 1,
                'uom_id' => 2,
                'cgst' => 9,
                'sgst' => 9,
                'igst' => 18,
                'cess' => 5,
                'hsncode' => 0313,
            ],
        ];

        foreach ($product as $row) {
            Product::create($row);
        }
    }
}
